DELETE http://localhost:3003/api/blogs/:id
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYXZrYXIiLCJpZCI6IjYyMTYxOWRlMGY4MjhjYmZmNjc4YWU5YSIsImlhdCI6MTY0NTYxNjIzNSwiZXhwIjoxNjQ1NjE5ODM1fQ.ufHg38qtgYu07hjychbaYOyqvAFiWnD5tYC50Necc4M